
image: danieldent/debian-base

# The script below purposefully does not specify rclone_layout.
# This is to test that the script works correctly when an optional
# parameter is not provided.

test:
  script:
    - mv git-annex-remote-rclone /usr/local/bin
    - curl 'https://downloads.kitenet.net/git-annex/linux/current/git-annex-standalone-amd64.tar.gz'|tar -xz -C /usr/local/bin --strip-components 1
    - curl 'https://downloads.rclone.org/rclone-current-linux-amd64.zip' > rclone.zip
    - unzip rclone.zip
    - mv rclone-*-linux-amd64/rclone /usr/local/bin
    - tests/all-in-one.sh
