name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-18.04
          # TODO: use datalad-installer for git-annex and may be rclone
          #- windows-2019
          #- macos-latest

    steps:
    - name: Set up environment
      uses: actions/checkout@v1
   
    - name: Install dependencies
      run: |
        curl 'https://downloads.kitenet.net/git-annex/linux/current/git-annex-standalone-amd64.tar.gz'|tar -xz -C /usr/local/bin --strip-components 1
        curl 'https://downloads.rclone.org/rclone-current-linux-amd64.zip' > rclone.zip
        unzip rclone.zip
        mv rclone-*-linux-amd64/rclone /usr/local/bin

    - name: ${{ matrix.module }} tests
      run: |
        tests/all-in-one.sh
