name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          #- windows-2019
          - macos-latest
        rclone:
          - current
          - v1.58.1  # current "current" -- the baseline
          - v1.53.3  # Debian bullseye (current stable)
          - v1.45    # Debian buster (current oldstable)
          # older versions for which there is internal logic
          - v1.33
          - v1.30
          # - v1.29 TODO: seems to need rclone config run -- must be done in test script
        exclude:
          # 1.45 - has some odd handling of HOME on OSX - does not use overloaded $HOME
          # 1.30 - --version exits non-0
          - os: macos-latest
            rclone: ['v1.30', 'v1.45']

    steps:
    - name: Set up environment
      uses: actions/checkout@v1

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '>=3.7'

    - name: Install datalad-installer
      run: pip install datalad-installer

    - name: Install git-annex (Ubuntu)
      if: startsWith(matrix.os, 'ubuntu-')
      run: datalad-installer --sudo ok git-annex -m datalad/git-annex:release

    - name: Install git-annex (macOS)
      if: startsWith(matrix.os, 'macos-')
      run: datalad-installer git-annex -m brew

    - name: Install latest rclone
      if: matrix.rclone == 'current'
      run: datalad-installer --sudo ok rclone -m downloads.rclone.org

    - name: Install specific version of rclone
      if: matrix.rclone != 'current'
      run: datalad-installer --sudo ok rclone=${{ matrix.rclone }} -m downloads.rclone.org

    - name: ${{ matrix.module }} tests
      run: |
        PATH=$PWD:$PATH tests/all-in-one.sh
